server:
  port: 9001

pring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/atd
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true